### ISSUE TITLE
配置1.19客户端无声

### ISSUE THREAD

**Issue by SkipM4** [BiliGoldenWater/ChaosMusicPlayer#1]
服务端: purpur-1.19-1659
插件版本: 1.0.2
在生成了材质包安装到客户端之后,在服务端放入wav,客户端点击播放出现进度条,但没有声音

**Comment by BillGoldenWater** [comment]
服务端: paper-1.19-13
客户端: vanilla-1.19-LWJGL_3.2.2_native
测试正常

建议游戏内使用: `/playsound minecraft:sine_wave.256_0 record @s` 测试资源包和音频设置是否正常
