### ISSUE TITLE
1.20.1服务器没声音

### ISSUE THREAD

**Issue by javakunraozhewo** [BiliGoldenWater/ChaosMusicPlayer#2]
1.20.1能成功加载插件1.1.2，客户端资源包也加载了，客户端mod也加载了，前置什么的都有，但是还是没声音。
服务器类型：Minecraft互通
服务器版本：paper-1.20.1
服务器互通插件：Geyser

启动器：Hello Minecraft! Launcher v3.5.4.234
客户端：1.20.1
客户端fabric版本：0.14.22
客户端fabric-api版本：0.87.0+1.20.1
mod前置：fabric-language-kotlin-1.10.8+kotlin.1.9.0

我能想到提供的信息就这么多了，进度条和设置全部有用，但就是没声音（虽然我知道插件写了版本只到1.19，但是既然1.20能加载进去，说明问题有可能可以解决/dogs）。

我平常不怎么关注github，所以消息没及时回复请见谅。感谢！

下面的图是证明我确实加载成功了插件
![9LI{$__(CY12_UMIQJR9}GK](https://github.com/BillGoldenWater/ChaosMusicPlayer/assets/115565832/fae3153a-7e3c-467a-ae68-eb595a60713b)
![I{V%`ZSUW~9C {S_A9_YBCX](https://github.com/BillGoldenWater/ChaosMusicPlayer/assets/115565832/365859dd-9338-494b-ba79-9934499783c6)

**Comment by javakunraozhewo** [comment]
补充一点新发现，在我现在截图让我选择截图区域的时候，突然出来了几秒的歌声，然后就再也没有了，我用的QQ截图，不知道这个能不能帮你更快的定位大概问题

**Comment by BillGoldenWater** [comment]
客户端的日志有吗

**Comment by javakunraozhewo** [comment]
这是完整的一份客户端日志，从游戏启动到结束




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BillGoldenWater/ChaosMusicPlayer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月24日(星期四) 凌晨0:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BillGoldenWater/ChaosMusicPlayer] 1.20.1服务器没声音 (Issue #2)





 
客户端的日志有吗

**Comment by javakunraozhewo** [comment]
邮箱发上来的在这里是不是看不见文件啊，我重新在这上传一次
[minecraft-exported-logs-2023-08-24T03-37-39.log](https://github.com/BillGoldenWater/ChaosMusicPlayer/files/12424264/minecraft-exported-logs-2023-08-24T03-37-39.log)

**Comment by BillGoldenWater** [comment]
umm, 看起来没有什么问题, 禁用mod只用资源包有声吗

**Comment by BillGoldenWater** [comment]
另外客户端与服务器间网络情况如何, 这个实现方式对网络质量要求较高, 可以本地试试有没有声

**Comment by javakunraozhewo** [comment]
我刚刚关闭mod直接加载资源包，播放音乐后客户端日志是这样的
[08:51:10] [Render thread/WARN]: Unable to play unknown soundEvent: minecraft:sine_wave.1024_0
[08:51:10] [Render thread/WARN]: Unable to play unknown soundEvent: minecraft:sine_wave.64_0
[08:51:10] [Render thread/WARN]: Unable to play unknown soundEvent: minecraft:sine_wave.256_0
[08:51:10] [Render thread/WARN]: Unable to play unknown soundEvent: minecraft:sine_wave.4096_0
[08:51:10] [Render thread/WARN]: Unable to play unknown soundEvent: minecraft:sine_wave.16_0
[08:51:10] [Render thread/WARN]: Unable to play unknown soundEvent: minecraft:sine_wave.16384_0

**Comment by javakunraozhewo** [comment]
我晚上试试本地开服务器有没有声音

**Comment by BillGoldenWater** [comment]
> 我刚刚关闭mod直接加载资源包，播放音乐后客户端日志是这样的
> [08:51:10] [Render thread/WARN]: Unable to play unknown soundEvent: minecraft:sine_wave.1024_0
> [08:51:10] [Render thread/WARN]: Unable to play unknown soundEvent: minecraft:sine_wave.64_0
> [08:51:10] [Render thread/WARN]: Unable to play unknown soundEvent: minecraft:sine_wave.256_0
> [08:51:10] [Render thread/WARN]: Unable to play unknown soundEvent: minecraft:sine_wave.4096_0
> [08:51:10] [Render thread/WARN]: Unable to play unknown soundEvent: minecraft:sine_wave.16_0
> [08:51:10] [Render thread/WARN]: Unable to play unknown soundEvent: minecraft:sine_wave.16384_0

umm, 要么资源包没生成好, 要么1.20改了格式不支持了

**Comment by javakunraozhewo** [comment]
> 

emmmm
